server:
  port: 8131

debug: true

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/v1/auth/**

        - id: enrollment-service
          uri: lb://enrollment-service
          predicates:
            - Path=/api/v1/enroll/**

        - id: identity-search-service
          uri: lb://identity-search-service
          predicates:
            - Path=/api/v1/search/**

        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/api/v1/identity/**

        - id: organisation-service
          uri: lb://organisation-service
          predicates:
            - Path=/api/v1/orgs/**
