server:
  port: 8131

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth/**

        - id: enrollment-service
          uri: lb://enrollment-service
          predicates:
            - Path=/enrol/**

        - id: identity-search-service
          uri: lb://identity-search-service
          predicates:
            - Path=/search/**

        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/identity/**

        - id: organisation-service
          uri: lb://organisation-service
          predicates:
            - Path=/organisation/**
